# Extension-specific rubocop config
# Does not inherit from parent (kiket repo uses rails-specific plugins)
#
# Run with: bundle exec rubocop --ignore-parent-exclusion
# The flag prevents scanning parent directories for exclude patterns

# Explicitly prevent inheritance from parent directories
inherit_from: []

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'Gemfile'

# Relaxed limits for extension code
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Layout/LineLength:
  Max: 150

# RSpec settings
RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

# Allow classes without documentation in scripts
Style/Documentation:
  Exclude:
    - 'bin/**/*'
