# Extension-specific rubocop config
# Does not inherit from parent (kiket repo uses rails-specific plugins)
#
# Run with: bundle exec rubocop --ignore-parent-exclusion
# The flag prevents scanning parent directories for exclude patterns

# Explicitly prevent inheritance from parent directories
inherit_from: []

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'Gemfile'

# Relaxed limits for extension code
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Very relaxed for existing extension code
Metrics/ClassLength:
  Max: 600

Metrics/MethodLength:
  Max: 80

Metrics/AbcSize:
  Max: 80

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ParameterLists:
  Max: 10

Layout/LineLength:
  Max: 180

# RSpec settings
RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

# Disable some style cops that conflict with existing code
Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false
