# Extension-specific rubocop config
# Does not inherit from parent (kiket repo uses rails-specific plugins)
#
# Run with: bundle exec rubocop --ignore-parent-exclusion
# The flag prevents scanning parent directories for exclude patterns

# Explicitly prevent inheritance from parent directories
inherit_from: []

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'

# Relaxed settings for extension code
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4
